In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#import dataset
sport_footwear = pd.read_csv('/content/drive/MyDrive/raw_data/global_sports_footwear_sales_2018_2026_ok.csv')

In [10]:
#read dataset
sport_footwear.head(5)
sport_footwear.shape
sport_footwear.columns
sport_footwear.info()
sport_footwear.describe()
sport_footwear.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               30000 non-null  object
 1   order_date             30000 non-null  object
 2   brand                  30000 non-null  object
 3   model_name             30000 non-null  object
 4   category               30000 non-null  object
 5   gender                 30000 non-null  object
 6   size                   30000 non-null  int64
 7   color                  30000 non-null  object
 8   base_price_usd         30000 non-null  int64
 9   discount_percent       30000 non-null  int64
 10  final_price_usd        30000 non-null  float64
 11  units_sold             30000 non-null  int64
 12  revenue_usd            30000 non-null  float64
 13  payment_method         30000 non-null  object
 14  sales_channel          30000 non-null  object
 15  country                30000 non-null  object
 16  customer_income_level  30000 non-null  object
 17  customer_rating        30000 non-null  float64
dtypes: float64(3), int64(4), object(11)
memory usage: 4.1+ MB

order_id                 0
order_date               0
brand                    0
model_name               0
category                 0
gender                   0
size                     0
color                    0
base_price_usd           0
discount_percent         0
final_price_usd          0
units_sold               0
revenue_usd              0
payment_method           0
sales_channel            0
country                  0
customer_income_level    0
customer_rating          0
dtype: int64

In [20]:
#changing data type
sport_footwear['order_date'] = pd.to_datetime(sport_footwear['order_date'])
sport_footwear.dtypes

order_id                         object
order_date               datetime64[ns]
brand                            object
model_name                       object
category                         object
gender                           object
size                              int64
color                            object
base_price_usd                    int64
discount_percent                  int64
final_price_usd                 float64
units_sold                        int64
revenue_usd                     float64
payment_method                   object
sales_channel                    object
country                          object
customer_income_level            object
customer_rating                 float64
dtype: object

In [29]:
#filtering data only until 2025
sales_2018_2025 = sport_footwear[sport_footwear['order_date'].dt.year <= 2025]

In [58]:
#EDA
total_revenue = sales_2018_2025['revenue_usd'].sum()
print(total_revenue)

total_units_sold = sales_2018_2025['units_sold'].sum()
print(total_units_sold)

average_price = sales_2018_2025['final_price_usd'].mean()
print(average_price)

revenue_year = sales_2018_2025.groupby(sales_2018_2025['order_date'].dt.year)['revenue_usd'].sum()
print(revenue_year)

yoy = revenue_year.pct_change() * 100
print(yoy)

revenue_vs_brand = sales_2018_2025.groupby('brand')['revenue_usd'].sum()
print(revenue_vs_brand)

categories_sold = sales_2018_2025.groupby('category')['units_sold'].sum()
print(categories_sold)

discount_sold = sales_2018_2025.groupby('discount_percent')['units_sold'].sum()
print(discount_sold)

channel_sold = sales_2018_2025.groupby('sales_channel')['units_sold'].sum()
print(channel_sold)

sales_country = sales_2018_2025.groupby('country').agg(
    total_revenue=('revenue_usd', 'sum'),
    total_units_sold=('units_sold', 'sum'),
    total_orders = ('order_id', 'nunique')
)
print(sales_country)

8084451.65
66773
121.05284552845528
order_date
2018     990380.20
2019    1029728.15
2020    1032345.75
2021     986065.65
2022    1026659.90
2023    1025135.90
2024     970039.25
2025    1024096.85
Name: revenue_usd, dtype: float64
order_date
2018         NaN
2019    3.973015
2020    0.254203
2021   -4.483004
2022    4.116790
2023   -0.148443
2024   -5.374570
2025    5.572723
Name: revenue_usd, dtype: float64
brand
ASICS          1391691.30
Adidas         1330874.20
New Balance    1357125.15
Nike           1349679.90
Puma           1331780.55
Reebok         1323300.55
Name: revenue_usd, dtype: float64
category
Basketball    13531
Gym           13088
Lifestyle     13509
Running       13302
Training      13343
Name: units_sold, dtype: int64
discount_percent
0     11020
5     11289
10    11069
15    10952
20    11210
30    11233
Name: units_sold, dtype: int64
sales_channel
Online          33267
Retail Store    33506
Name: units_sold, dtype: int64
          total_revenue  total_units_sold  total_orders
country
Germany      1321787.45             10971          4366
India        1352538.30             11136          4439
Pakistan     1312496.85             10778          4316
UAE          1377276.30             11422          4561
UK           1361932.85             11263          4504
USA          1358419.90             11203          4505